from __future__ import annotations

from datetime import datetime, timezone
from typing import Any

import pandas as pd
from sqlalchemy import func, select

from ...config import settings
from ...db import SessionLocal
from ...models import (
    BacktestRun,
    ForwardRun,
    OOSRun,
    SpikeEvent,
    StrategyAgent,
    StrategyCandidate,
    StrategyMetric,
    StrategyStatusHistory,
    SystemEvent,
)
from ...symbol_profiles import get_profile
from ..backtest import chronological_split
from .agents import AGENT_SPECS, generate_candidate_payloads
from .evaluator import evaluate_candidate
from .leaderboard import FORMULA_DESCRIPTION, leaderboard_rows, refresh_leaderboard
from .qualification import parameter_sensitivity_test, quality_score, qualification_gate


def _canonical_symbol(symbol: str) -> str:
    return get_profile(symbol).symbol


def _period(df: pd.DataFrame) -> dict | None:
    if df.empty:
        return None
    return {"start_epoch": int(df.iloc[0]["epoch"]), "end_epoch": int(df.iloc[-1]["epoch"]), "bars": int(len(df))}


def _without_events(spike_metrics: dict) -> dict:
    out = dict(spike_metrics)
    out.pop("events", None)
    return out


def _strategy_dict(candidate: StrategyCandidate) -> dict:
    return {
        "id": candidate.id,
        "name": candidate.name,
        "agent_name": candidate.agent_name,
        "symbol": candidate.symbol,
        "version": candidate.version,
        "parameters": candidate.parameters or {},
        "rules": candidate.rules or [],
        "indicators_used": candidate.indicators_used or [],
        "timeframes": candidate.timeframes or [],
        "training_period": candidate.training_period,
        "validation_period": candidate.validation_period,
        "status": candidate.status,
        "creation_time": candidate.created_at.isoformat() if candidate.created_at else None,
    }


class ArenaPipeline:
    @staticmethod
    def seed_agents(db) -> None:
        for spec in AGENT_SPECS.values():
            exists = db.execute(select(StrategyAgent).where(StrategyAgent.name == spec.name)).scalar_one_or_none()
            if exists:
                continue
            db.add(
                StrategyAgent(
                    name=spec.name,
                    description=spec.description,
                    capabilities=spec.capabilities,
                    enabled=True,
                )
            )
        db.flush()

    @staticmethod
    def bootstrap_mvp(db) -> None:
        ArenaPipeline.seed_agents(db)
        for symbol in settings.arena_mvp_symbols:
            ArenaPipeline.generate(db, symbol=symbol, variants_per_agent=2)
        db.commit()

    @staticmethod
    def agents(db) -> list[dict]:
        ArenaPipeline.seed_agents(db)
        db.commit()
        rows = db.execute(select(StrategyAgent).order_by(StrategyAgent.id)).scalars().all()
        return [
            {
                "id": r.id,
                "name": r.name,
                "description": r.description,
                "capabilities": r.capabilities,
                "enabled": bool(r.enabled),
            }
            for r in rows
        ]

    @staticmethod
    def generate(db, symbol: str, agent_name: str | None = None, variants_per_agent: int = 2) -> list[dict]:
        symbol = _canonical_symbol(symbol)
        ArenaPipeline.seed_agents(db)
        payloads = generate_candidate_payloads(symbol, agent_name, variants_per_agent)
        created = []
        for payload in payloads:
            candidate = db.get(StrategyCandidate, payload["id"])
            if not candidate:
                candidate = StrategyCandidate(**payload)
                db.add(candidate)
                db.add(
                    StrategyStatusHistory(
                        strategy_id=candidate.id,
                        from_status=None,
                        to_status="created",
                        reason="candidate generated by Strategy Agent",
                    )
                )
                created.append(candidate)
            else:
                created.append(candidate)
        db.flush()
        return [_strategy_dict(c) for c in created]

    @staticmethod
    def list_strategies(db, symbol: str | None = None, agent: str | None = None, status: str | None = None) -> list[dict]:
        stmt = select(StrategyCandidate)
        if symbol:
            stmt = stmt.where(StrategyCandidate.symbol == _canonical_symbol(symbol))
        if agent:
            stmt = stmt.where(StrategyCandidate.agent_name == agent)
        if status:
            stmt = stmt.where(StrategyCandidate.status == status)
        rows = db.execute(stmt.order_by(StrategyCandidate.created_at.desc())).scalars().all()
        return [_strategy_dict(r) for r in rows]

    @staticmethod
    def _transition(db, candidate: StrategyCandidate, new_status: str, reason: str) -> None:
        old = candidate.status
        if old == new_status:
            return
        candidate.status = new_status
        db.add(
            StrategyStatusHistory(
                strategy_id=candidate.id,
                from_status=old,
                to_status=new_status,
                reason=reason,
            )
        )
        db.flush()

    @staticmethod
    def _persist_metric(db, strategy_id: str, stage: str, result: dict) -> StrategyMetric:
        metric = StrategyMetric(
            strategy_id=strategy_id,
            stage=stage,
            metrics=result["metrics"],
            spike_metrics=_without_events(result["spike_metrics"]),
            equity_curve=result["equity_curve"],
            drawdown_curve=result["drawdown_curve"],
        )
        db.add(metric)
        db.flush()
        return metric

    @staticmethod
    def _persist_spike_events(db, strategy_id: str, symbol: str, result: dict) -> None:
        for event in result["spike_metrics"].get("events", []):
            exists = db.execute(
                select(SpikeEvent.id).where(
                    SpikeEvent.strategy_id == strategy_id,
                    SpikeEvent.epoch == event["epoch"],
                    SpikeEvent.signal_epoch == event["signal_epoch"],
                )
            ).scalar_one_or_none()
            if exists:
                continue
            db.add(
                SpikeEvent(
                    symbol=symbol,
                    strategy_id=strategy_id,
                    epoch=event["epoch"],
                    side=event["side"],
                    magnitude_atr=event.get("magnitude_atr"),
                    detected_by_signal=True,
                    signal_epoch=event.get("signal_epoch"),
                    lead_time_seconds=event.get("lead_time_seconds"),
                    mae_before_spike=event.get("mae_before_spike"),
                    mfe_after_signal=event.get("mfe_after_signal"),
                )
            )

    @staticmethod
    def backtest(db, strategy_id: str, candles: list[dict]) -> dict:
        candidate = db.get(StrategyCandidate, strategy_id)
        if not candidate:
            raise KeyError("Strategy not found")
        profile = get_profile(candidate.symbol)
        df = pd.DataFrame(candles).sort_values("epoch").reset_index(drop=True)
        train_ratio = settings.arena_train_ratio
        validation_ratio = settings.arena_validation_ratio
        train, validation, holdout = chronological_split(df, train_ratio, validation_ratio)
        if min(len(train), len(validation), len(holdout)) < 80:
            raise ValueError("Dataset is too small for 60/20/20 anti-overfitting split; each segment needs at least 80 bars")

        ArenaPipeline._transition(db, candidate, "backtesting", "historical in-sample and validation backtest started")
        candidate.training_period = _period(train)
        candidate.validation_period = _period(validation)

        in_sample = evaluate_candidate(train, candidate, profile)
        validation_result = evaluate_candidate(validation, candidate, profile)
        ArenaPipeline._persist_metric(db, candidate.id, "in_sample", in_sample)
        ArenaPipeline._persist_metric(db, candidate.id, "validation", validation_result)
        ArenaPipeline._persist_spike_events(db, candidate.id, candidate.symbol, validation_result)

        gate = qualification_gate(validation_result["metrics"], validation_result["spike_metrics"], "validation")
        new_status = "qualified" if gate["passed"] else "rejected"
        ArenaPipeline._transition(db, candidate, new_status, "qualification gate passed" if gate["passed"] else f"qualification failed: {', '.join(gate['failed'])}")

        run = BacktestRun(
            symbol=candidate.symbol,
            status=new_status,
            params={
                "strategy_id": candidate.id,
                "agent_name": candidate.agent_name,
                "split": {"train": train_ratio, "validation": validation_ratio, "oos": 1 - train_ratio - validation_ratio},
                "parameters": candidate.parameters,
            },
            metrics=validation_result["metrics"],
        )
        db.add(run)
        refresh_leaderboard(db, candidate.id)
        db.add(
            SystemEvent(
                level="INFO",
                event_type="arena_backtest_complete",
                message=f"{candidate.id} -> {new_status}",
                payload={"strategy_id": candidate.id, "symbol": candidate.symbol, "gate": gate},
            )
        )
        db.commit()
        db.refresh(run)

        return {
            "run_id": run.id,
            "strategy": _strategy_dict(candidate),
            "in_sample_results": {
                "metrics": in_sample["metrics"],
                "spike_metrics": _without_events(in_sample["spike_metrics"]),
            },
            "validation_results": {
                "metrics": validation_result["metrics"],
                "spike_metrics": _without_events(validation_result["spike_metrics"]),
            },
            "qualification": gate,
            "oos_holdout": _period(holdout),
        }

    @staticmethod
    def oos_test(db, strategy_id: str, candles: list[dict], train_ratio: float | None = None, validation_ratio: float | None = None) -> dict:
        candidate = db.get(StrategyCandidate, strategy_id)
        if not candidate:
            raise KeyError("Strategy not found")
        if candidate.status not in {"qualified", "oos_testing"}:
            raise ValueError(f"Strategy must be qualified before OOS testing; current status={candidate.status}")

        tr = train_ratio if train_ratio is not None else settings.arena_train_ratio
        va = validation_ratio if validation_ratio is not None else settings.arena_validation_ratio
        if tr + va >= 0.95:
            raise ValueError("Train + validation ratio leaves insufficient OOS holdout")

        df = pd.DataFrame(candles).sort_values("epoch").reset_index(drop=True)
        train, validation, oos = chronological_split(df, tr, va)
        if min(len(validation), len(oos)) < 80:
            raise ValueError("Validation and OOS segments each need at least 80 bars")

        profile = get_profile(candidate.symbol)
        ArenaPipeline._transition(db, candidate, "oos_testing", "out-of-sample test started")
        oos_result = evaluate_candidate(oos, candidate, profile)
        gate = qualification_gate(oos_result["metrics"], oos_result["spike_metrics"], "oos")
        robustness = parameter_sensitivity_test(validation, candidate, profile)
        passed = gate["passed"] and robustness["passed"]

        ArenaPipeline._persist_metric(db, candidate.id, "out_of_sample", oos_result)
        db.add(
            StrategyMetric(
                strategy_id=candidate.id,
                stage="robustness",
                metrics=robustness,
                spike_metrics={},
                equity_curve=None,
                drawdown_curve=None,
            )
        )
        ArenaPipeline._persist_spike_events(db, candidate.id, candidate.symbol, oos_result)
        row = OOSRun(
            strategy_id=candidate.id,
            split_config={"train": tr, "validation": va, "oos": 1 - tr - va},
            metrics=oos_result["metrics"],
            spike_metrics=_without_events(oos_result["spike_metrics"]),
            status="passed" if passed else "failed",
        )
        db.add(row)
        ArenaPipeline._transition(
            db,
            candidate,
            "forward_testing" if passed else "retired",
            "OOS + robustness passed" if passed else f"OOS/robustness failed; gate={gate['failed']}, robustness={robustness['passed']}",
        )
        refresh_leaderboard(db, candidate.id)
        db.add(
            SystemEvent(
                level="INFO",
                event_type="arena_oos_complete",
                message=f"{candidate.id} -> {'forward_testing' if passed else 'retired'}",
                payload={"strategy_id": candidate.id, "gate": gate, "robustness": robustness},
            )
        )
        db.commit()
        db.refresh(row)

        return {
            "oos_run_id": row.id,
            "strategy": _strategy_dict(candidate),
            "out_of_sample_results": {
                "metrics": oos_result["metrics"],
                "spike_metrics": _without_events(oos_result["spike_metrics"]),
                "quality_score": quality_score(oos_result["metrics"], oos_result["spike_metrics"]),
            },
            "robustness_check": robustness,
            "qualification": gate,
        }

    @staticmethod
    def detail(db, strategy_id: str) -> dict:
        candidate = db.get(StrategyCandidate, strategy_id)
        if not candidate:
            raise KeyError("Strategy not found")

        metrics_rows = db.execute(
            select(StrategyMetric).where(StrategyMetric.strategy_id == strategy_id).order_by(StrategyMetric.id)
        ).scalars().all()
        results = {}
        for row in metrics_rows:
            results[row.stage] = {
                "metrics": row.metrics,
                "spike_metrics": row.spike_metrics,
                "equity_curve": row.equity_curve,
                "drawdown_curve": row.drawdown_curve,
            }

        history = db.execute(
            select(StrategyStatusHistory)
            .where(StrategyStatusHistory.strategy_id == strategy_id)
            .order_by(StrategyStatusHistory.id.desc())
            .limit(50)
        ).scalars().all()
        forward = db.execute(
            select(ForwardRun).where(ForwardRun.strategy_id == strategy_id).order_by(ForwardRun.id.desc()).limit(10)
        ).scalars().all()

        recent_events = db.execute(select(SystemEvent).order_by(SystemEvent.id.desc()).limit(250)).scalars().all()
        recent_signals = [
            {
                "id": e.id,
                "event_type": e.event_type,
                "created_at": e.created_at.isoformat() if e.created_at else None,
                "payload": e.payload,
            }
            for e in recent_events
            if (e.payload or {}).get("strategy_id") == strategy_id and e.event_type in {"arena_shadow_signal", "arena_shadow_result"}
        ][:50]

        return {
            **_strategy_dict(candidate),
            "backtest_results": results.get("in_sample"),
            "validation_results": results.get("validation"),
            "oos_results": results.get("out_of_sample"),
            "robustness_results": results.get("robustness"),
            "forward_results": [
                {
                    "id": r.id,
                    "mode": r.mode,
                    "duration_hours": r.duration_hours,
                    "status": r.status,
                    "metrics": r.metrics,
                    "last_error": r.last_error,
                    "started_at": r.started_at.isoformat() if r.started_at else None,
                    "ended_at": r.ended_at.isoformat() if r.ended_at else None,
                }
                for r in forward
            ],
            "recent_signals": recent_signals,
            "status_history": [
                {
                    "from": h.from_status,
                    "to": h.to_status,
                    "reason": h.reason,
                    "created_at": h.created_at.isoformat() if h.created_at else None,
                }
                for h in history
            ],
        }

    @staticmethod
    def leaderboard(db, symbol: str | None = None, agent: str | None = None, status: str | None = None) -> dict:
        return {
            "formula": FORMULA_DESCRIPTION,
            "weights": settings.arena_composite_weights,
            "rows": leaderboard_rows(db, symbol=symbol, agent=agent, status=status),
        }

    @staticmethod
    def activity(db, limit: int = 100) -> list[dict]:
        rows = db.execute(
            select(SystemEvent)
            .where(SystemEvent.event_type.like("arena_%"))
            .order_by(SystemEvent.id.desc())
            .limit(min(limit, 500))
        ).scalars().all()
        return [
            {
                "id": r.id,
                "level": r.level,
                "event_type": r.event_type,
                "message": r.message,
                "payload": r.payload,
                "created_at": r.created_at.isoformat() if r.created_at else None,
            }
            for r in rows
        ]

    @staticmethod
    def stats(db) -> dict[str, Any]:
        start = datetime.now(timezone.utc).replace(hour=0, minute=0, second=0, microsecond=0).replace(tzinfo=None)
        total = db.scalar(select(func.count()).select_from(StrategyCandidate)) or 0
        by_status = {}
        for status in ["created", "backtesting", "rejected", "qualified", "oos_testing", "forward_testing", "retired"]:
            by_status[status] = db.scalar(
                select(func.count()).select_from(StrategyCandidate).where(StrategyCandidate.status == status)
            ) or 0
        agents = db.scalar(select(func.count()).select_from(StrategyAgent).where(StrategyAgent.enabled.is_(True))) or 0
        backtests_today = db.scalar(
            select(func.count()).select_from(BacktestRun).where(BacktestRun.created_at >= start)
        ) or 0
        shadow_today = db.scalar(
            select(func.count()).select_from(SystemEvent).where(
                SystemEvent.event_type == "arena_shadow_signal",
                SystemEvent.created_at >= start,
            )
        ) or 0
        return {
            "total_strategies": total,
            "qualified": by_status["qualified"],
            "rejected": by_status["rejected"],
            "oos_testing": by_status["oos_testing"],
            "forward_testing": by_status["forward_testing"],
            "active_agents": agents,
            "backtests_today": backtests_today,
            "shadow_signals_today": shadow_today,
            "status_counts": by_status,
            "mvp_symbols": settings.arena_mvp_symbols,
        }


def bootstrap_arena() -> None:
    with SessionLocal() as db:
        ArenaPipeline.bootstrap_mvp(db)
