import { useEffect, useMemo, useState } from 'react';
import { Activity, ArrowDownRight, ArrowUpRight, BookOpen, ChartCandlestick, ChevronDown, CircleHelp, ExternalLink, Eye, FlaskConical, Layers3, Maximize2, RefreshCw, ShieldCheck, X } from 'lucide-react';
import MarketChart from './MarketChart';
import { useDerivMarket, type Bar, type Timeframe } from './lib/deriv';
import { getCRT, type CRTAnalysis } from './lib/crt';

const SAFETY = Object.freeze({ LIVE_TRADING: false, READY_FOR_LIVE: false, LIVE_ALLOWED: false, OPENED_TRADES: false });
const periods = { M1: 60, M5: 300, M15: 900, H1: 3600 };
const number = (v: number | null | undefined, places = 3) => v == null || !Number.isFinite(v) ? '—' : v.toLocaleString('en-US', { minimumFractionDigits: places, maximumFractionDigits: places });
const clock = (epoch: number | null | undefined, seconds = false) => !epoch ? '—' : new Date(epoch * 1000).toLocaleTimeString('ar-SA', { hour: '2-digit', minute: '2-digit', ...(seconds ? { second: '2-digit' } : {}), hour12: false, timeZone: 'Asia/Riyadh' });
const stateCopy = {
  waiting: ['بانتظار سحب السيولة', 'يبدأ الرصد بعد تجاوز حد النطاق في الاتجاه المطلوب.'],
  sweep: ['رُصد سحب السيولة', 'ننتظر إغلاق M5 داخل الحدين خلال ثلاث شموع.'],
  reclaimed: ['استُعيد النطاق', 'أغلق السعر داخل الحدين. نرصد تأكيد MSS والإزاحة والفجوة.'],
  confirmed: ['اكتملت التأكيدات', 'اجتمعت الشروط على شمعة M5 مغلقة. هذه ملاحظة تحليلية.'],
  invalid: ['أُلغي النموذج', 'لم يعد الإعداد صالحًا بعد تجاوز حدود الإبطال أو فشل الاستعادة.'],
  expired: ['انتهت مهلة النموذج', 'انتهت نافذة الإعداد. تبقى التأكيدات السابقة ملاحظات تاريخية.'],
} as const;
const eventCopy: Record<string, string> = { sweep: 'سحب السيولة', reclaim: 'استعادة النطاق', mss: 'تحول الهيكل', displacement: 'إزاحة سعرية', fvg: 'فجوة سعرية', invalid: 'إلغاء النموذج', expired: 'انتهاء المهلة' };

function StatePanel({ crt, stale, family }: { crt: CRTAnalysis | null, stale: boolean, family: 'boom' | 'crash' }) {
  const stage = crt?.state ?? 'waiting';
  const reached = stage === 'confirmed' ? 3 : stage === 'reclaimed' || stage === 'expired' ? 2 : stage === 'sweep' || (crt?.events.some(e => e.type === 'sweep') ?? false) ? 1 : 0;
  const [headline, detail] = stateCopy[stage];
  return <section className="setup-panel panel"><div className="section-heading"><div><span className="eyebrow">نظرية نطاق الشمعة</span><h2>نموذج CRT الحالي</h2></div><Layers3 size={18} /></div>
    <div className={'setup-state ' + stage}><span className="state-dot" /><strong>{stale ? 'البيانات تحتاج تحديثًا' : crt ? headline : 'جارٍ تحميل النطاق'}</strong></div>
    <p className="setup-detail">{stale ? 'ستُستأنف قراءة النموذج عند عودة البيانات الحديثة.' : crt ? detail : 'يلزم مرجع H1 كامل وبيانات M5 مغلقة لقراءة النموذج.'}</p>
    <ol className="crt-steps">{[['نطاق مرجعي', 'أعلى وأدنى آخر شمعة H1 مغلقة'], ['سحب السيولة', family === 'crash' ? 'تجاوز CRH ثم مراقبة العودة' : 'تجاوز CRL ثم مراقبة العودة'], ['استعادة النطاق', 'إغلاق M5 داخل الحدين'], ['تأكيد الهيكل', 'MSS + إزاحة + FVG على إغلاق M5']].map(([title, description], i) => <li className={i <= reached && crt ? 'reached' : ''} key={title}><span className="step-number">{i === 0 ? <Layers3 size={13} /> : i}</span><div><strong>{title}</strong><small>{description}</small></div>{i === reached && crt && <span className="step-live" />}</li>)}</ol>
    <div className="confirmation-grid">{[['MSS', crt?.mss], ['الإزاحة', crt?.displacement], ['FVG', Boolean(crt?.fvg)]].map(([label, active]) => <div className={active ? 'observed' : ''} key={String(label)}><span className="mini-dot" />{label}<small>{active ? 'رُصدت' : 'بانتظارها'}</small></div>)}</div>
    <div className="context-note"><CircleHelp size={15} /><span>اكتمال النموذج لا يعني ضمان انفجار أو نتيجة رابحة.</span></div></section>;
}

function Dialog({ kind, close }: { kind: 'guide' | 'research', close: () => void }) {
  return <div className="modal-backdrop" onClick={close}><section className="modal panel" role="dialog" aria-modal="true" aria-labelledby="dialog-title" onClick={e => e.stopPropagation()}><button className="icon-button modal-close" onClick={close} aria-label="إغلاق النافذة"><X size={20} /></button>
    <span className="eyebrow">{kind === 'guide' ? 'دليل قراءة الشارت' : 'بيانات تاريخية · 180 يومًا'}</span><h2 id="dialog-title">{kind === 'guide' ? 'من النطاق إلى التأكيد' : 'ما الذي أثبته الاختبار؟'}</h2>
    {kind === 'guide' ? <><p>نحدد CRH وCRL من آخر ساعة مغلقة بالكامل. على Boom نرصد سحبًا أسفل CRL، وعلى Crash نرصد سحبًا أعلى CRH، ثم إغلاق M5 داخل الحدين.</p><div className="guide-range"><span>CRH · أعلى النطاق</span><span>50% · منتصف النطاق</span><span>CRL · أدنى النطاق</span></div><p>السحب المقبول: 0.10–0.65 من ATR السابق. الاستعادة خلال شمعة السحب أو الشمعتين التاليتين. مهلة التأكيد تشمل الاستعادة وثلاث شموع M5 تالية. تُحسب المؤشرات والعلامات من الشموع المغلقة فقط.</p><p>المنطقة المظللة هي الساعة المرجعية. تغيير فريم العرض لا يغيّر مرجع H1 أو تأكيد M5. اسحب الرسم أو استخدم عجلة الفأرة للتقريب. محور الرسم بتوقيت UTC، ووقت الملاحظات بتوقيت الرياض.</p></> : <><p>جرى الاختبار على Boom 500 وCrash 500 بفصل زمني 70/30 وثلاث نوافذ تحقق. التعريف أدناه حركة 2×ATR خلال 15 دقيقة.</p><div className="research-table"><table><thead><tr><th>النموذج</th><th>الدقة</th><th>الطبيعي</th><th>الإشارات</th></tr></thead><tbody><tr><td>Boom 500 · CRT</td><td>25.76%</td><td>22.22%</td><td>229</td></tr><tr><td>Crash 500 · CRT</td><td>18.98%</td><td>21.61%</td><td>216</td></tr><tr><td>Crash 500 · محاذاة المقاومة</td><td>30.52%</td><td>21.61%</td><td>639</td></tr></tbody></table></div><p className="research-caveat">CRT الخام لم يثبت تفوقًا إحصائيًا. محاذاة المقاومة على Crash فرضية للمتابعة على بيانات جديدة. هذه الأرقام تخص هذين الرمزين والتعريف المذكور؛ ربحية التداول والتكاليف والاختبار الأمامي غير مختبرة.</p><a className="text-link" href="https://github.com/zyadixx-oss/boom-crash-quant-lab/blob/spike-hunter-validation-20261004/docs/spike_hunter_20261004/REPORT.ar.md" target="_blank" rel="noreferrer">التقرير الكامل وفترات الثقة <ExternalLink size={14} /></a></>}
    <div className="context-note"><ShieldCheck size={17} /><span>الموقع للتحليل والمراقبة. جميع أعلام التداول الأربعة معطلة، ولا يفتح صفقات.</span></div></section></div>;
}

export default function App() {
  const [selected, setSelected] = useState(() => localStorage.getItem('crt.symbol') || 'BOOM500');
  const [timeframe, setTimeframe] = useState<Timeframe>('M5');
  const [showCRT, setShowCRT] = useState(true), [showMarkers, setShowMarkers] = useState(true);
  const [dialog, setDialog] = useState<'guide' | 'research' | null>(null);
  const [crosshair, setCrosshair] = useState<Bar | null>(null), [expanded, setExpanded] = useState(false);
  const market = useDerivMarket(selected, timeframe);
  const family = selected.startsWith('CRASH') ? 'crash' : 'boom';
  const profile = market.symbols.find(s => s.id === selected);
  const crt = useMemo(() => getCRT(market.analysisBars, family, market.lastTickEpoch ?? undefined), [market.analysisBars, family, market.lastTickEpoch]);
  const chartCRT = useMemo(() => crt ? { range: { high: crt.high, low: crt.low, mid: crt.midpoint, start: crt.refStart, end: crt.refEnd }, events: crt.history.filter(e => ['sweep', 'reclaim', 'mss', 'displacement', 'fvg'].includes(e.type)).map(e => ({ time: e.time, type: e.type as 'sweep' | 'reclaim' | 'mss' | 'displacement' | 'fvg', direction: family as 'boom' | 'crash' })) } : null, [crt, family]);
  const displayBar = crosshair ?? market.bars.at(-1) ?? null;
  const lastClosed = market.bars.filter(b => b.time + periods[timeframe] <= (market.lastTickEpoch ?? 0)).at(-1);
  const connected = market.status === 'connected' && !market.isStale;
  const statusText = connected ? 'بيانات مباشرة' : market.status === 'error' ? 'تعذّر الاتصال' : market.isStale && market.status === 'connected' ? 'البيانات متأخرة' : market.status === 'reconnecting' ? 'إعادة الاتصال' : 'جارٍ الاتصال';
  useEffect(() => { localStorage.setItem('crt.symbol', selected); setCrosshair(null); }, [selected, timeframe]);
  useEffect(() => { if (market.symbols.length && !market.symbols.some(s => s.id === selected)) setSelected(market.symbols.some(s => s.id === 'BOOM500') ? 'BOOM500' : market.symbols[0].id); }, [market.symbols, selected]);
  useEffect(() => { const onKey = (e: KeyboardEvent) => { if (e.key === 'Escape') { setDialog(null); setExpanded(false); } }; document.addEventListener('keydown', onKey); return () => document.removeEventListener('keydown', onKey); }, []);

  return <div className="app-shell"><header className="site-header"><a className="brand" href="#" aria-label="نطاق — الصفحة الرئيسية"><span className="brand-mark"><i /><i /></span><div><strong>نطاق<span className="brand-dot">.</span></strong><small>BOOM / CRASH · CRT</small></div></a><nav className="header-nav" aria-label="التنقل"><button className="nav-active"><ChartCandlestick size={16} />الشارت</button><button onClick={() => setDialog('research')}><FlaskConical size={16} />نتائج الدراسة</button><button onClick={() => setDialog('guide')}><BookOpen size={16} />دليل CRT</button></nav><div className="header-status"><span className={'connection-pill ' + (connected ? 'online' : 'pending')}><i />{statusText}</span><span className="analysis-pill"><ShieldCheck size={14} />تحليل فقط</span></div></header>
    <main className="workspace"><div className="page-heading"><div><span className="eyebrow">مرصد نطاق الشمعة</span><h1>اقرأ النطاق. راقب الحركة.</h1><p>شموع مباشرة ونموذج CRT لكل رمز من Boom وCrash.</p></div><div className="heading-aside"><Activity size={17} /><span>مصدر الأسعار <strong>Deriv</strong><small>واجهة البيانات العامة</small></span></div></div>
    <section className="market-toolbar panel" aria-label="إعدادات الشارت"><div className="symbol-field"><label htmlFor="symbol">الرمز</label><div className="select-wrap"><select id="symbol" value={selected} onChange={e => setSelected(e.target.value)}>{market.symbols.length ? ['boom', 'crash'].map(f => <optgroup label={f === 'boom' ? 'رموز Boom' : 'رموز Crash'} key={f}>{market.symbols.filter(s => s.family === f).map(s => <option value={s.id} key={s.id}>{s.label}</option>)}</optgroup>) : <option value={selected}>{selected} · جارٍ تحميل الرموز</option>}</select><ChevronDown size={15} /></div></div><div className="family-toggle" aria-label="عائلة الرمز"><button className={family === 'boom' ? 'active boom' : ''} onClick={() => setSelected('BOOM500')}><ArrowUpRight size={16} />Boom</button><button className={family === 'crash' ? 'active crash' : ''} onClick={() => setSelected('CRASH500')}><ArrowDownRight size={16} />Crash</button></div><div className="toolbar-separator" /><div className="timeframes"><span>فريم العرض</span><div>{(['M1', 'M5', 'M15', 'H1'] as Timeframe[]).map(tf => <button className={tf === timeframe ? 'active' : ''} key={tf} onClick={() => setTimeframe(tf)}>{tf}</button>)}</div></div><div className="reference-tag"><Layers3 size={14} /><span>مرجع <b>H1</b><small>تأكيد M5</small></span></div><button className="icon-button refresh" onClick={market.retry} aria-label="إعادة الاتصال وتحديث البيانات" title="تحديث البيانات"><RefreshCw size={17} /></button></section>
    <section className="metric-strip" aria-label="ملخص الرمز"><div className="metric"><span>السعر الحالي <i className={connected ? 'live-dot' : ''} /></span><strong className="price" dir="ltr">{number(market.price)}</strong><small>{profile?.label || selected}</small></div><div className="metric"><span><i className="range-key high" />أعلى النطاق · CRH</span><strong dir="ltr">{number(crt?.high)}</strong><small>آخر ساعة مغلقة</small></div><div className="metric"><span><i className="range-key low" />أدنى النطاق · CRL</span><strong dir="ltr">{number(crt?.low)}</strong><small>مرجع {clock(crt?.refStart)}–{clock(crt?.refEnd)}</small></div><div className="metric"><span><i className="range-key mid" />منتصف النطاق · 50%</span><strong dir="ltr">{number(crt?.midpoint)}</strong><small>وقت الرياض · {clock(market.lastTickEpoch, true)}</small></div></section>
    <div className="chart-layout"><section className={'chart-panel panel ' + (expanded ? 'chart-expanded' : '')}><div className="chart-heading"><div><h2>{profile?.label || selected}<span className={'direction-tag ' + family}>{family === 'boom' ? <ArrowUpRight size={12} /> : <ArrowDownRight size={12} />}{family === 'boom' ? 'رصد الاتجاه الصاعد' : 'رصد الاتجاه الهابط'}</span></h2><div className="ohlc-row" dir="ltr">{[['O', displayBar?.open], ['H', displayBar?.high], ['L', displayBar?.low], ['C', displayBar?.close]].map(([key, value]) => <span key={String(key)}><em>{key}</em>{number(value as number | undefined)}</span>)}</div></div><div className="chart-actions"><button className="icon-button" onClick={() => setDialog('guide')} aria-label="مساعدة الشارت"><CircleHelp size={17} /></button><button className="icon-button" onClick={() => setExpanded(v => !v)} aria-label={expanded ? 'تصغير الشارت' : 'تكبير الشارت'}>{expanded ? <X size={17} /> : <Maximize2 size={17} />}</button></div></div>
      {market.bars.length ? <MarketChart key={selected + '-' + timeframe} bars={market.bars} crt={chartCRT} showCRT={showCRT} showMarkers={showMarkers} onCrosshair={setCrosshair} /> : <div className="chart-empty"><ChartCandlestick size={42} /><strong>{market.status === 'error' ? 'لم تصل بيانات الأسعار' : 'جارٍ تحميل الشموع'}</strong><p>{market.error || 'الاتصال ببيانات Deriv العامة وتحميل السجل الحقيقي.'}</p>{market.status === 'error' && <button className="primary-button" onClick={market.retry}><RefreshCw size={15} />إعادة المحاولة</button>}</div>}
      {market.bars.length > 0 && !connected && <div className="chart-connection-note"><i />{statusText} · {market.error || 'آخر أسعار مستلمة ظاهرة على الشارت'}</div>}
      <div className="chart-footer"><div className="chart-options"><button className={showCRT ? 'selected' : ''} onClick={() => setShowCRT(v => !v)} aria-pressed={showCRT}><Layers3 size={14} />نطاق CRT</button><button className={showMarkers ? 'selected' : ''} onClick={() => setShowMarkers(v => !v)} aria-pressed={showMarkers}><Eye size={14} />علامات النموذج</button></div><span>{market.bars.length.toLocaleString('ar-SA')} شمعة · {timeframe}<small>الإشارات من الشموع المغلقة</small></span></div></section>
      <aside><StatePanel crt={crt} stale={market.isStale} family={family} /><section className="observation-panel panel"><div className="section-heading"><h2>آخر الملاحظات</h2><span className="count-badge">{crt?.history.length || 0}</span></div>{crt?.history.length ? <ul className="event-list">{crt.history.slice(-5).reverse().map((event, i) => <li key={event.type + '-' + event.time + '-' + i}><span className={'event-icon ' + event.type} /><div><strong>{eventCopy[event.type]}</strong><small>{number(event.price)}</small></div><time>{clock(event.time)}</time></li>)}</ul> : <div className="quiet-state"><Activity size={22} /><p>لا توجد ملاحظات CRT ضمن السجل المحمّل.</p></div>}</section></aside></div>
    <section className="bottom-context"><div><span className="live-dot" /><strong>سوق يعمل طوال الأسبوع</strong><span>{market.symbols.length || '—'} رمزًا · القائمة تُحدّث من Deriv</span></div><div><span>آخر شمعة مغلقة</span><b>{clock(lastClosed ? lastClosed.time + periods[timeframe] : null)}</b><span>·</span><span>سحب → استعادة → تأكيد</span></div></section>
    <footer className="site-footer"><span>نطاق · مراقبة CRT على بيانات عامة. التداول معطل.</span><div><a href="https://www.tradingview.com/" target="_blank" rel="noreferrer">الرسوم بواسطة TradingView</a><button onClick={() => setDialog('research')}>حدود النتائج</button></div><details><summary>إعدادات الأمان</summary><div dir="ltr">{Object.entries(SAFETY).map(([key, value]) => <code key={key}>{key}={String(value)}</code>)}</div></details></footer></main>
    {dialog && <Dialog kind={dialog} close={() => setDialog(null)} />}</div>;
}
