import React,{useEffect,useMemo,useState} from 'react';import {createRoot} from 'react-dom/client';import {Activity,ShieldCheck,Radio,Telescope,BarChart3,FlaskConical,GitCompareArrows} from 'lucide-react';import MarketChart from './MarketChart';import './index.css';
type Profile={symbol:string,display_name:string,min_signal_score:number,spike_atr_multiple:number};type Tab='dashboard'|'signals'|'backtest'|'compare';
type Bar={time:number,open:number,high:number,low:number,close:number};
function App(){const [symbols,setSymbols]=useState<Profile[]>([]),[status,setStatus]=useState<any>(null),[tick,setTick]=useState<any>(null),[selected,setSelected]=useState('BOOM500'),[tab,setTab]=useState<Tab>('dashboard'),[bars,setBars]=useState<Bar[]>([]),[signals,setSignals]=useState<any[]>([]),[board,setBoard]=useState<any[]>([]);
useEffect(()=>{fetch('/api/health').then(r=>r.json()).then(setStatus);fetch('/api/symbols').then(r=>r.json()).then(setSymbols);fetch('/api/signals?limit=40').then(r=>r.json()).then(setSignals);fetch('/api/leaderboard').then(r=>r.json()).then(setBoard)},[]);
useEffect(()=>{fetch(`/api/market/history/${selected}?count=300&timeframe=M1`).then(r=>r.ok?r.json():[]).then((x:any[])=>setBars(x.map(c=>({time:c.epoch,open:c.open,high:c.high,low:c.low,close:c.close})))).catch(()=>setBars([]));const ws=new WebSocket(`${location.protocol==='https:'?'wss':'ws'}://${location.host}/ws/market?symbol=${selected}`);ws.onmessage=e=>{try{setTick(JSON.parse(e.data))}catch{}};return()=>ws.close()},[selected]);
const best=useMemo(()=>board.filter(x=>x.symbol===selected)[0],[board,selected]);
return <main className="max-w-7xl mx-auto p-6 space-y-6"><header className="flex flex-wrap items-center justify-between gap-4"><div><h1 className="text-3xl font-bold">Boom/Crash Quant Lab</h1><p className="muted">Statistical research • Backtest • Shadow signals</p></div><div className="card flex gap-2 items-center"><ShieldCheck className="good"/><span>SHADOW ONLY</span></div></header>
<nav className="flex gap-2 flex-wrap">{([['dashboard','Dashboard',BarChart3],['signals','Live Signals',Radio],['backtest','Backtests',FlaskConical],['compare','Compare',GitCompareArrows]] as const).map(([id,label,Icon])=><button key={id} onClick={()=>setTab(id)} className={`px-4 py-2 rounded-xl flex gap-2 ${tab===id?'bg-slate-700':'bg-slate-900'}`}><Icon size={17}/>{label}</button>)}</nav>
<section className="grid md:grid-cols-4 gap-4"><div className="card"><p className="muted">System</p><b className="good">{status?.status?.toUpperCase()||'...'}</b></div><div className="card"><p className="muted">Trading</p><b className="good">DISABLED</b></div><div className="card"><p className="muted">Last price</p><b>{tick?.price??'Waiting'}</b></div><div className="card"><p className="muted">Symbol</p><select className="bg-slate-900 p-2 rounded" value={selected} onChange={(e:React.ChangeEvent<HTMLSelectElement>)=>setSelected(e.target.value)}>{symbols.map(s=><option key={s.symbol}>{s.symbol}</option>)}</select></div></section>
{tab==='dashboard'&&<><section className="card"><h2 className="text-xl font-semibold mb-2">Real Deriv M1 candles</h2>{bars.length?<MarketChart bars={bars}/>:<p className="muted">Chart appears when the Backend can reach Deriv and returns candle history.</p>}</section><section><h2 className="text-xl font-semibold mb-3 flex gap-2"><Telescope/>Symbol Profiles</h2><div className="grid sm:grid-cols-2 lg:grid-cols-5 gap-3">{symbols.map(s=><button onClick={()=>setSelected(s.symbol)} key={s.symbol} className="card text-left hover:border-slate-500"><div className="flex justify-between"><b>{s.display_name}</b><Activity size={18}/></div><p className="muted text-sm">Min score {s.min_signal_score}</p><p className="text-xs"><Radio className="inline" size={12}/> M1 / M5 / M15</p></button>)}</div></section></>}
{tab==='signals'&&<section className="card overflow-auto"><h2 className="text-xl font-semibold mb-3">Recorded signals</h2><table className="w-full text-sm"><thead><tr><th>Symbol</th><th>Score</th><th>Direction</th><th>Reasons</th></tr></thead><tbody>{signals.map(x=><tr key={x.id}><td>{x.symbol}</td><td>{x.score}</td><td>{x.direction}</td><td>{x.reason_codes?.join(', ')}</td></tr>)}</tbody></table>{!signals.length&&<p className="muted">No stored signals yet. Shadow collection does not fabricate signals.</p>}</section>}
{tab==='backtest'&&<section className="grid md:grid-cols-3 gap-4"><div className="card"><p className="muted">Best recorded run</p><b>{best?.status||'NOT TESTED'}</b></div><div className="card"><p className="muted">Profit factor</p><b>{best?.profit_factor??'—'}</b></div><div className="card"><p className="muted">Expectancy</p><b>{best?.expectancy??'—'}</b></div><div className="card md:col-span-3"><p className="muted">Run backtests via POST /backtest with real chronological candles. Test data is never used by the optimizer.</p></div></section>}
{tab==='compare'&&<section className="card overflow-auto"><h2 className="text-xl font-semibold mb-3">Symbol comparison</h2><table className="w-full text-sm"><thead><tr><th>Symbol</th><th>Min score</th><th>Spike ATR seed</th><th>Latest PF</th><th>Latest Expectancy</th></tr></thead><tbody>{symbols.map(s=>{const r=board.find(x=>x.symbol===s.symbol);return <tr key={s.symbol}><td>{s.display_name}</td><td>{s.min_signal_score}</td><td>{s.spike_atr_multiple}</td><td>{r?.profit_factor??'NOT TESTED'}</td><td>{r?.expectancy??'NOT TESTED'}</td></tr>})}</tbody></table></section>}
<section className="card"><h2 className="text-xl font-semibold">Research guardrails</h2><p className="muted">Scores are not probabilities. No fake performance. No live order execution. Only measured backtest/shadow observations may support claims.</p></section></main>}
createRoot(document.getElementById('root')!).render(<React.StrictMode><App/></React.StrictMode>)
